# Generated by Django 3.1.2 on 2020-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('phone_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=145)),
                ('book_photo', models.ImageField(blank=True, upload_to='book_photos')),
            ],
        ),
    ]
